# Generated by Django 5.0.1 on 2025-11-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="audio_duration_seconds",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="voice_messages/"),
        ),
        migrations.AddField(
            model_name="message",
            name="audio_mime_type",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
